### PR TITLE
feat(profile): deactivate user profile

### PR DESCRIPTION
**Pull request by Okeke12nancy**
Description:

This feature is to provide an endpoint that allows users to deactivate their profiles. When a user deactivates their profile, the backend should handle the necessary actions to disable their account while preserving relevant data.

Purpose:

To give users control over their profiles by allowing them to deactivate their accounts when needed. Deactivation ensures privacy and compliance with user preferences.

Acceptance Criteria:

The endpoint should be able to accept a user’s request to deactivate their profile. (only the user can deactivate their own profile)

Upon successful deactivation, update the user’s profile status to “deactivated” in the database and ensure that deactivated profiles cannot log in or perform any actions.

Users without the necessary permissions should receive a 403 Forbidden status code such as unauthorized access or database errors

Update the user's profile status to 'deactivated' in the database.

Ensure that the deactivation status is correctly reflected in the user's profile settings

Return a success message and the updated profile status

Endpoint: '/api/v1/settings/profiles/deactivate-profile'

Expected Outcomes:

Users can deactivate their profiles via the provided endpoint.

Deactivated profiles are appropriately updated in the database.

Relevant data is retained while ensuring compliance with privacy regulations

Testing:

### CODE REVIEW

**Comment by TheCodeGhinux** [comment]
Your test are failing

**Comment by davidolanrewaju** [comment]
This feature has been implemented and merged in the previous stage. This is a link to the merged [PR](https://github.com/hngprojects/hng_boilerplate_nestjs/pull/406)

**Comment by Okeke12nancy** [comment]
> This feature has been implemented and merged in the previous stage. This is a link to the merged [PR](https://github.com/hngprojects/hng_boilerplate_nestjs/pull/406)

**Comment by Okeke12nancy** [comment]
@davidolanrewaju mine is deactivate user profile. Check the linear ticket.

**Pull request closed without merging**
